### ISSUE TITLE
Greetings from Saun

### ISSUE THREAD

**Issue by gematro** [Alektryon/gematro#1]
Good day, Luis!

This is Saun Virroco (author of original Gematro calculator).

It is kind of sad to see how so many people misuse gematria and what insanities come out of it.

This is one of the many reasons why I closed my project back in November 2022 as I failed to see the point of maintaining it.
There was just enough educational materials I had to share with people and the lack of enthusiasm (both from me and users) caused me to move on and keep exploring other unchartered waters on my own.

Still, almost a year later, I made the decision to reinstate the original repository with one of my latest local versions.

Not that I'm back with new groundbreaking stuff, no.
I just don't like some wannabe superstars who desperately try to steal the spotlight with yet another branded fork.
I'd rather have you maintaining the repository than allow some forkus (circus, fork, focus?).

Even though I am always critical of something, we agree on many parts.
No one else is capable of making at least some sense of gematria.

You explicitly asked me for permission to make custom versions, so did digitaldimension via email, I approved it a long time ago. Others never asked.

Some kept pissing me off, so that I leave everything behind and they quietly take my stuff when I'm finally gone.
A couple of bad actors can ruin the whole show.

Feels like my project was hijacked to endorse some shizo "decodes", when it was aimed to do the opposite - to teach, to motivate, to inspire the learning process, to promote mathematics, geometry, number theory, coding, to encourage exploration of ancient wisdom, to embark on the search for the lost word, etc.

Sadly, reasoning doesn't always work with some people. Not with covert narcissists.
If they drive you insane, drive them away. And that's the only way.
I saw what I had to see, I learned what I had to learn.

Nevertheless, I am grateful to you, and Tim (not sure if he's still around), and a few other reasonable men for the good conversations we held together back in the days. It was productive. At least in some ways.

Felt like a lodge experience, if you know what I mean.

I'd appreciate if you could share the news since the original "clean" version is available online at https://gematro.github.io/.

I might share some good olde audiobooke resource as well - https://www.youtube.com/@MasterKeySociety/videos

By the way, I've long switched to a different email, so my old contacts are gone.
And, there are lots of things to be focused on.

As always, take care.

**Comment by Alektryon** [comment]
Hi Mikhail,

I believe you're doing this because @malonehunter made a modification of
Gematro and called it "Hyperdope Gematria". Which is cool, and I agree with
you that a calculator that looks *exactly *like Gematro should be called
the same way, and that your work as the maker of Gematro should be
respected and not misrepresented. Either way, I never saw @malonehunter
trying to make people believe that he was the maker of Gematro, or even to
try misrepresent your opinion as being the same as his. After all, I
published two copies of Gematro (in different stages of evolution) but I
never tried to impersonate you or to tell people that your opinions are the
same as mine — which they definitely *aren't*.

It's curious to note that you say that you didn't see the point of
maintaining a project like Gematro when there were lots of people using it,
even preferring it over Gematrinator. I always said the same, and I always
will. It's far better than Gematrinator — but if there are more people
using it, who don't understand a thing about Gematria, rather than people
that actually understand how Gematria works, that definitely isn't a
problem to the calculator itself. A calculator is meant to be *used*, and
there are no calculators like Gematro all over the internet. Well, at least
having so many tools as Gematro has.

I also find it funny that you say that this is a "clean" version of
Gematro. To be honest, I find it quite *poor*, at least in terms of
ciphers. And I think that this only demonstrates that, in your anxiety to
"teach" people what Gematria is (and what they should do, and what they
should *think*, by the way), you entirely missed the point — maybe
motivated by the bad example that Gematrinator is — that the more ciphers a
calculator has, the more confusing Gematria will be to people. And it's
only confusing if you use all ciphers at the same time, because in that
case you're doing exactly the same bullshit that Derek does: that is, to
try to find a "pattern" where there isn't one, or even to say that someone
encoded something because you find that a phrase has "significant" values
in 10 different ciphers. Wow.

Gematria is not the same as cherry picking numerical matches amongst a
chaotic mess of experimental ciphers. A good work with Gematria isn't
measured by the number of ciphers you use. In fact, it's precisely the
*opposite*. It doesn't matter how many ciphers your calculator has — you
can have a thousand ciphers in your calculator, but what it really matters
is that the ciphers make sense in their own context, and that you use the
*correct* ciphers to decode the *correct* things. Do you think my work is
comparable to Derek's, just because my copy of Gematro has 46 ciphers (not
counting the Extra ciphers)? Poor misguided fool...You never actually
understood how I work with Gematria, let alone what my beliefs are, or what
I should study, or what I shouldn't study.

It's also noteworthy the aversion you have to Alphanumeric Qabbala, even to
the point of completely removing it from the calculator. If you're worried
about the "Ccru-BoogeyMan" coming after you if you include that cipher in
the calculator, let me ask you one thing, then: How did I write my longest
and most deeply coded text on Alphanumeric Qabbala
<https://gematriaresearch.blogspot.com/2023/02/the-wonders-magic-of-alphanumeric.html>,
without mentioning the Ccru, or even Nick Land, even *once*? And have you
ever heard about the "Wow!" Signal, a.k.a. "6EQUJ5"? Even if this doesn't
prove that Alphanumeric Qabbala is a valid cipher for the English alphabet,
it *definitely* proves that the sequence from 0 to Z was used as an
alphanumeric string of digits (i.e. base36 notation) at least as far back
as 1975. And if even in this case you still think that AQ should be avoided
because it doesn't make sense (which it *does*) — have you ever thought
about why Alphanumeric Qabbala (or, in fact, base36 notation) only appeared
during the age of computers? What does that tell you, now that we're on the
verge of a fundamental change in our lives, motivated precisely by the rise
of Artificial Intelligence?

So with this said, I guess that I don't have any interest in maintaining
your repository.
Nor will I waste my time advertising your new version of Gematro, only to
see it disappear again because it was your momentary whim to delete it.

I will, however, add a link to your original so-called "clean" version of
Gematro to my main, most up-to-date fork of Gematro, as I think that all
credit for Gematro should be given to you alone. Like I always said.
I will also change the "Contacts" menu to be more like the one you have in
this modern version of your calculator. So I'm doing you a favor, which
most people wouldn't do. Especially after what you told me — and *about me*.

The rest? Well, the rest I don't need it. In fact, if you're so bored
about @malonehunter having changed your calculator, you should then face
people and stop with your tricks and intrigues. I have passed beyond that
phase, and to be honest with you, I've distanced myself from most
Gematria-related "communities", simply because they never brought me
anything good. Even my server was given away to Tim, who definitely is a
cool and wise guy. In fact, maybe you didn't know this, but the fact is
that I have a new job which is much better than my previous one, so I have
to focus on what is really important to me. I don't care about you, or
Gematria, or your dramas. But I don't have anything against
you, personally. You did a great job, I respect it, and that's it.

I will definitely follow your work on @MasterKeySociety, though. It looks
good.
*That one* I may share with it more people. Anything that helps people
being better people is most welcome.

Take care,

LG



gematro ***@***.***> escreveu no dia segunda, 30/10/2023 à(s)
21:24:
